package commands

import (
	"os"
	"path/filepath"

	"github.com/gofastadev/cli/internal/clierr"
	"github.com/spf13/cobra"
)

var configCmd = &cobra.Command{
	Use:   "config",
	Short: "Inspect and validate the project's config.yaml",
	Long: `Tools that operate on the project's configuration surface —
currently just the schema emitter, more subcommands to come.

Subcommands:
  schema    Emit the JSON Schema (Draft 7) describing config.yaml

See ` + "`gofasta config <sub> --help`" + ` for the specific subcommand.`,
}

var configSchemaCmd = &cobra.Command{
	Use:   "schema",
	Short: "Emit the JSON Schema describing config.yaml",
	Long: `Emit a JSON Schema (Draft 7) that describes the shape of config.yaml.
The schema is generated by reflecting over the AppConfig type in the
gofasta library version this project uses — there is no second source
of truth to keep in sync.

Intended consumers:
  - Editor extensions (VS Code YAML, JetBrains) that consume JSON
    Schema for autocomplete, inline type errors, and enum suggestions.
    Add ` + "`# yaml-language-server: $schema=./config.schema.json`" + ` to
    the top of config.yaml to opt in.
  - CI pipelines that validate config.yaml before deploy.
  - AI coding agents editing config.yaml programmatically.

Implementation note: this command shells out to ` + "`go run ./cmd/schema`" + `
inside the project directory. Running in-project means the emitted
schema reflects the exact gofasta version pinned in go.mod, not the
version the CLI binary was compiled against — a concrete benefit when
project and CLI versions drift.

Examples:
  gofasta config schema                    # print to stdout
  gofasta config schema > config.schema.json
  gofasta config schema | jq .properties.database`,
	RunE: func(cmd *cobra.Command, args []string) error {
		return runConfigSchema()
	},
}

func init() {
	configCmd.GroupID = groupWorkflow
	configCmd.AddCommand(configSchemaCmd)
	rootCmd.AddCommand(configCmd)
}

// runConfigSchema shells out to the project's own ./cmd/schema helper
// so the emitted JSON Schema always matches the gofasta/pkg/config
// version the project pins. Keeping the reflection code out of the CLI
// binary is a deliberate architectural choice — the CLI intentionally
// does not import the library.
func runConfigSchema() error {
	helperPath := filepath.Join("cmd", "schema")
	if _, err := os.Stat(helperPath); err != nil {
		return clierr.Newf(clierr.CodeNotGofastaProject,
			"./cmd/schema/ not found — is this a gofasta project? Run this command from the project root")
	}

	cmd := execCommand("go", "run", "./"+helperPath)
	// The subprocess writes JSON (pretty-printed by the helper) — both
	// text and --json modes stream the same bytes, so no branching.
	// Piping stdout through directly avoids buffering large schemas in
	// the CLI process.
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		return clierr.Wrap(clierr.CodeGeneratorFailed, err,
			"failed to run ./cmd/schema")
	}
	return nil
}
