package templates

// Controller is the Go template for generating a REST controller.
//
// Validation lives at this boundary; service-layer sentinel errors
// are translated to HTTP status codes via apperrors. The service
// returns *models.X — this layer maps to DTOs for the response.
var Controller = `package controllers

import (
	"errors"
	"net/http"

	"github.com/go-chi/chi/v5"
	apperrors "github.com/gofastadev/gofasta/pkg/errors"
	"github.com/gofastadev/gofasta/pkg/httputil"
	"github.com/gofastadev/gofasta/pkg/utils"
	"github.com/gofastadev/gofasta/pkg/validators"
	"gorm.io/gorm"

	"{{.ModulePath}}/app/dtos"
	"{{.ModulePath}}/app/services"
	svcInterfaces "{{.ModulePath}}/app/services/interfaces"
)

// {{.Name}}Controller exposes the REST surface for the {{.Name}} resource.
// Generated by ` + "`gofasta g controller`" + `. Owns input binding,
// validation, and the model→DTO mapping for responses; delegates the
// actual work to the service layer.
type {{.Name}}Controller struct {
	svc       svcInterfaces.{{.Name}}ServiceInterface
	validator *validators.AppValidator
}

// New{{.Name}}ControllerInstance constructs a {{.Name}}Controller.
// Wire calls this at app startup.
func New{{.Name}}ControllerInstance(svc svcInterfaces.{{.Name}}ServiceInterface, v *validators.AppValidator) *{{.Name}}Controller {
	return &{{.Name}}Controller{svc: svc, validator: v}
}

// List handles GET /{{.PluralLower}}.
{{- if .IncludeSwagger}}
//
//	@Summary		List {{.PluralLower}}
//	@Description	Get all {{.PluralLower}} with optional filtering, pagination, and sorting
//	@Tags			{{.PluralLower}}
//	@Produce		json
//	@Param			sortByField		query		string	false	"Field to sort by (default: createdAt)"
//	@Param			sortOrientation	query		string	false	"asc | desc (default: desc)"
//	@Success		200				{object}	dtos.T{{.PluralName}}ResponseDto
//	@Failure		422				{object}	apperrors.AppError
//	@Failure		500				{object}	apperrors.AppError
//	@Router			/{{.PluralLower}} [get]
{{- end}}
func (c *{{.Name}}Controller) List(w http.ResponseWriter, r *http.Request) error {
	q, err := httputil.BindQuery[dtos.T{{.Name}}FiltersQueryParamsDto](r)
	if err != nil {
		return apperrors.NewBadRequest("invalid query parameters", nil)
	}
	if errs := c.validator.ValidateStruct(q); len(errs) > 0 {
		return apperrors.NewValidation("invalid query parameters", errs)
	}
	f := q.ToFilter()
	entities, total, err := c.svc.List(r.Context(), f)
	if err != nil {
		return apperrors.NewInternal("failed to fetch {{.PluralLower}}", err)
	}
	totalRecords := int(total)
	totalPages := 0
	if f.Limit > 0 {
		totalPages = (totalRecords + f.Limit - 1) / f.Limit
	}
	return httputil.OK(w, dtos.T{{.PluralName}}ResponseDto{
		Data: dtos.{{.PluralName}}FromModels(entities),
		Pagination: &dtos.TPaginationObjectDto{
			TotalRecords:   &totalRecords,
			CurrentPage:    &f.Page,
			RecordsPerPage: &f.Limit,
			TotalPages:     &totalPages,
		},
	})
}

// GetByID handles GET /{{.PluralLower}}/{id}.
{{- if .IncludeSwagger}}
//
//	@Summary		Get a {{.LowerName}}
//	@Description	Get a single {{.LowerName}} by ID
//	@Tags			{{.PluralLower}}
//	@Produce		json
//	@Param			id	path		string	true	"{{.Name}} ID"
//	@Success		200	{object}	dtos.T{{.Name}}ResponseDto
//	@Failure		400	{object}	apperrors.AppError
//	@Failure		404	{object}	apperrors.AppError
//	@Failure		500	{object}	apperrors.AppError
//	@Router			/{{.PluralLower}}/{id} [get]
{{- end}}
func (c *{{.Name}}Controller) GetByID(w http.ResponseWriter, r *http.Request) error {
	id, err := utils.ParseIDStringIsValidUUID(chi.URLParam(r, "id"))
	if err != nil {
		return apperrors.NewBadRequest("id should be a valid UUID", nil)
	}
	entity, err := c.svc.Get(r.Context(), id)
	switch {
	case errors.Is(err, services.Err{{.Name}}NotFound), errors.Is(err, gorm.ErrRecordNotFound):
		return apperrors.NewNotFound("{{.LowerName}} not found", nil)
	case err != nil:
		return apperrors.NewInternal("failed to find {{.LowerName}}", err)
	}
	return httputil.OK(w, dtos.T{{.Name}}ResponseDto{Data: dtos.{{.Name}}FromModel(entity)})
}

// Create handles POST /{{.PluralLower}}.
{{- if .IncludeSwagger}}
//
//	@Summary		Create a {{.LowerName}}
//	@Description	Create a new {{.LowerName}}
//	@Tags			{{.PluralLower}}
//	@Accept			json
//	@Produce		json
//	@Param			{{.LowerName}}	body		dtos.TCreate{{.Name}}Dto	true	"{{.Name}} data"
//	@Success		201				{object}	dtos.T{{.Name}}ResponseDto
//	@Failure		422				{object}	apperrors.AppError
//	@Failure		500				{object}	apperrors.AppError
//	@Router			/{{.PluralLower}} [post]
{{- end}}
func (c *{{.Name}}Controller) Create(w http.ResponseWriter, r *http.Request) error {
	in, err := httputil.BindJSON[dtos.TCreate{{.Name}}Dto](r)
	if err != nil {
		return apperrors.NewBadRequest("invalid request body", nil)
	}
	if errs := c.validator.ValidateStruct(in); len(errs) > 0 {
		return apperrors.NewValidation("invalid input", errs)
	}
	entity, err := c.svc.Create(r.Context(), in.ToCreateInput())
	if err != nil {
		return apperrors.NewInternal("failed to create {{.LowerName}}", err)
	}
	return httputil.Created(w, dtos.T{{.Name}}ResponseDto{Data: dtos.{{.Name}}FromModel(entity)})
}

// Update handles PUT /{{.PluralLower}}/{id}.
{{- if .IncludeSwagger}}
//
//	@Summary		Update a {{.LowerName}}
//	@Description	Update {{.LowerName}} fields by ID
//	@Tags			{{.PluralLower}}
//	@Accept			json
//	@Produce		json
//	@Param			id				path		string						true	"{{.Name}} ID"
//	@Param			{{.LowerName}}	body		dtos.TUpdate{{.Name}}Dto	true	"Fields to update"
//	@Success		200				{object}	dtos.T{{.Name}}ResponseDto
//	@Failure		400				{object}	apperrors.AppError
//	@Failure		404				{object}	apperrors.AppError
//	@Failure		409				{object}	apperrors.AppError	"record version mismatch"
//	@Failure		422				{object}	apperrors.AppError
//	@Failure		500				{object}	apperrors.AppError
//	@Router			/{{.PluralLower}}/{id} [put]
{{- end}}
func (c *{{.Name}}Controller) Update(w http.ResponseWriter, r *http.Request) error {
	id, err := utils.ParseIDStringIsValidUUID(chi.URLParam(r, "id"))
	if err != nil {
		return apperrors.NewBadRequest("id should be a valid UUID", nil)
	}
	in, err := httputil.BindJSON[dtos.TUpdate{{.Name}}Dto](r)
	if err != nil {
		return apperrors.NewBadRequest("invalid request body", nil)
	}
	in.ID = id
	if errs := c.validator.ValidateStruct(in); len(errs) > 0 {
		return apperrors.NewValidation("invalid input", errs)
	}
	entity, err := c.svc.Update(r.Context(), id, in.RecordVersion, in.ToPatch())
	switch {
	case errors.Is(err, services.Err{{.Name}}VersionConflict):
		return apperrors.NewConflict("record version mismatch — refetch and retry", nil)
	case errors.Is(err, services.Err{{.Name}}NotFound), errors.Is(err, gorm.ErrRecordNotFound):
		return apperrors.NewNotFound("{{.LowerName}} not found", nil)
	case err != nil:
		return apperrors.NewInternal("failed to update {{.LowerName}}", err)
	}
	return httputil.OK(w, dtos.T{{.Name}}ResponseDto{Data: dtos.{{.Name}}FromModel(entity)})
}

// Archive handles DELETE /{{.PluralLower}}/{id}. Returns 204 on success.
{{- if .IncludeSwagger}}
//
//	@Summary		Archive a {{.LowerName}}
//	@Description	Soft-delete a {{.LowerName}} by ID
//	@Tags			{{.PluralLower}}
//	@Param			id	path	string	true	"{{.Name}} ID"
//	@Success		204
//	@Failure		400	{object}	apperrors.AppError
//	@Failure		409	{object}	apperrors.AppError	"{{.LowerName}} is not deletable"
//	@Failure		500	{object}	apperrors.AppError
//	@Router			/{{.PluralLower}}/{id} [delete]
{{- end}}
func (c *{{.Name}}Controller) Archive(w http.ResponseWriter, r *http.Request) error {
	id, err := utils.ParseIDStringIsValidUUID(chi.URLParam(r, "id"))
	if err != nil {
		return apperrors.NewBadRequest("id should be a valid UUID", nil)
	}
	err = c.svc.Archive(r.Context(), id)
	switch {
	case errors.Is(err, services.Err{{.Name}}NotDeletable):
		return apperrors.NewConflict("{{.LowerName}} is not deletable", nil)
	case err != nil:
		return apperrors.NewInternal("failed to archive {{.LowerName}}", err)
	}
	return httputil.NoContent(w)
}
`
