package templates

// Controller is the Go template for generating a REST controller.
//
// Validation lives at this boundary; service-layer sentinel errors
// are translated to HTTP status codes via apperrors. The service
// returns *models.X — this layer maps to DTOs for the response.
var Controller = `package controllers

import (
	"errors"
	"net/http"
	"strconv"

	"github.com/go-chi/chi/v5"
	apperrors "github.com/gofastadev/gofasta/pkg/errors"
	"github.com/gofastadev/gofasta/pkg/httputil"
	"github.com/gofastadev/gofasta/pkg/utils"
	"gorm.io/gorm"

	"{{.ModulePath}}/app/dtos"
	"{{.ModulePath}}/app/services"
	svcInterfaces "{{.ModulePath}}/app/services/interfaces"
)

// {{.LowerName}}RecordVersionETag formats a record version as the ETag
// value the {{.LowerName}} responses set on Get / Create / Update /
// Archive. The quoting matches what httputil.ParseIfMatch unquotes so
// a client round-trip (GET → If-Match → PUT) is symmetric.
func {{.LowerName}}RecordVersionETag(v int) string {
	return httputil.ETagOf(strconv.Itoa(v))
}

// {{.Name}}Controller exposes the REST surface for the {{.Name}} resource.
// Generated by ` + "`gofasta g controller`" + `. Owns input binding,
// validation, and the model→DTO mapping for responses; delegates the
// actual work to the service layer.
type {{.Name}}Controller struct {
	svc       svcInterfaces.{{.Name}}ServiceInterface
	validator Validator
}

// New{{.Name}}ControllerInstance constructs a {{.Name}}Controller.
// Wire calls this at app startup. Validator is the controllers.Validator
// interface; the project's *validators.AppValidator is bound to it in
// providers.CoreSet.
func New{{.Name}}ControllerInstance(svc svcInterfaces.{{.Name}}ServiceInterface, v Validator) *{{.Name}}Controller {
	return &{{.Name}}Controller{svc: svc, validator: v}
}

// List handles GET /{{.PluralLower}}.
{{- if .IncludeSwagger}}
//
//	@Summary		List {{.PluralLower}}
//	@Description	Get all {{.PluralLower}} with optional filtering, pagination, and sorting
//	@Tags			{{.PluralLower}}
//	@Produce		json
//	@Param			sortByField		query		string	false	"Field to sort by (default: createdAt)"
//	@Param			sortOrientation	query		string	false	"asc | desc (default: desc)"
//	@Success		200				{object}	dtos.T{{.PluralName}}ResponseDto
//	@Failure		422				{object}	apperrors.AppError
//	@Failure		500				{object}	apperrors.AppError
//	@Router			/{{.PluralLower}} [get]
{{- end}}
func (c *{{.Name}}Controller) List(w http.ResponseWriter, r *http.Request) error {
	q, err := httputil.DecodeQuery[dtos.T{{.Name}}FiltersQueryParamsDto](r)
	if err != nil {
		return apperrors.NewBadRequest("invalid query parameters", nil)
	}
	if errs := c.validator.ValidateStruct(q); len(errs) > 0 {
		return apperrors.NewValidation("invalid query parameters", errs)
	}
	f := q.ToFilter()
	entities, total, err := c.svc.List(r.Context(), f)
	if err != nil {
		return apperrors.NewInternal("failed to fetch {{.PluralLower}}", err)
	}
	totalRecords := int(total)
	totalPages := 0
	if f.Limit > 0 {
		totalPages = (totalRecords + f.Limit - 1) / f.Limit
	}
	return httputil.OK(w, dtos.T{{.PluralName}}ResponseDto{
		Data: dtos.{{.PluralName}}FromModels(entities),
		Pagination: &dtos.TPaginationObjectDto{
			TotalRecords:   &totalRecords,
			CurrentPage:    &f.Page,
			RecordsPerPage: &f.Limit,
			TotalPages:     &totalPages,
		},
	})
}

// GetByID handles GET /{{.PluralLower}}/{id}.
{{- if .IncludeSwagger}}
//
//	@Summary		Get a {{.LowerName}}
//	@Description	Get a single {{.LowerName}} by ID
//	@Tags			{{.PluralLower}}
//	@Produce		json
//	@Param			id	path		string	true	"{{.Name}} ID"
//	@Success		200	{object}	dtos.T{{.Name}}ResponseDto
//	@Failure		400	{object}	apperrors.AppError
//	@Failure		404	{object}	apperrors.AppError
//	@Failure		500	{object}	apperrors.AppError
//	@Router			/{{.PluralLower}}/{id} [get]
{{- end}}
func (c *{{.Name}}Controller) GetByID(w http.ResponseWriter, r *http.Request) error {
	id, err := utils.ParseIDStringIsValidUUID(chi.URLParam(r, "id"))
	if err != nil {
		return apperrors.NewBadRequest("id should be a valid UUID", nil)
	}
	entity, err := c.svc.Get(r.Context(), id)
	switch {
	case errors.Is(err, services.Err{{.Name}}NotFound), errors.Is(err, gorm.ErrRecordNotFound):
		return apperrors.NewNotFound("{{.LowerName}} not found", nil)
	case err != nil:
		return apperrors.NewInternal("failed to find {{.LowerName}}", err)
	}
	w.Header().Set("ETag", {{.LowerName}}RecordVersionETag(entity.RecordVersion))
	return httputil.OK(w, dtos.T{{.Name}}ResponseDto{Data: dtos.{{.Name}}FromModel(entity)})
}

// Create handles POST /{{.PluralLower}}.
{{- if .IncludeSwagger}}
//
//	@Summary		Create a {{.LowerName}}
//	@Description	Create a new {{.LowerName}}
//	@Tags			{{.PluralLower}}
//	@Accept			json
//	@Produce		json
//	@Param			{{.LowerName}}	body		dtos.TCreate{{.Name}}Dto	true	"{{.Name}} data"
//	@Success		201				{object}	dtos.T{{.Name}}ResponseDto
//	@Failure		422				{object}	apperrors.AppError
//	@Failure		500				{object}	apperrors.AppError
//	@Router			/{{.PluralLower}} [post]
{{- end}}
func (c *{{.Name}}Controller) Create(w http.ResponseWriter, r *http.Request) error {
	in, err := httputil.DecodeJSON[dtos.TCreate{{.Name}}Dto](r)
	if err != nil {
		return apperrors.NewBadRequest("invalid request body", nil)
	}
	if errs := c.validator.ValidateStruct(in); len(errs) > 0 {
		return apperrors.NewValidation("invalid input", errs)
	}
	entity, err := c.svc.Create(r.Context(), in.ToCreateInput())
	if err != nil {
		return apperrors.NewInternal("failed to create {{.LowerName}}", err)
	}
	w.Header().Set("ETag", {{.LowerName}}RecordVersionETag(entity.RecordVersion))
	return httputil.Created(w, dtos.T{{.Name}}ResponseDto{Data: dtos.{{.Name}}FromModel(entity)})
}

// Update handles PUT /{{.PluralLower}}/{id}. Optimistic concurrency
// control uses HTTP-native If-Match / ETag (RFC 7232): caller GETs to
// fetch the ETag, then PUTs with If-Match: "<version>". 412 on
// mismatch, 428 when the header is missing.
{{- if .IncludeSwagger}}
//
//	@Summary		Update a {{.LowerName}}
//	@Description	Update {{.LowerName}} fields by ID. Send the current RecordVersion as ` + "`If-Match: \"<n>\"`" + `.
//	@Tags			{{.PluralLower}}
//	@Accept			json
//	@Produce		json
//	@Param			id				path		string						true	"{{.Name}} ID"
//	@Param			If-Match		header		string						true	"Current RecordVersion (e.g. \"3\")"
//	@Param			{{.LowerName}}	body		dtos.TUpdate{{.Name}}Dto	true	"Fields to update"
//	@Success		200				{object}	dtos.T{{.Name}}ResponseDto
//	@Failure		400				{object}	apperrors.AppError
//	@Failure		404				{object}	apperrors.AppError
//	@Failure		412				{object}	apperrors.AppError	"If-Match doesn't match current version"
//	@Failure		422				{object}	apperrors.AppError
//	@Failure		428				{object}	apperrors.AppError	"If-Match header is required"
//	@Failure		500				{object}	apperrors.AppError
//	@Router			/{{.PluralLower}}/{id} [put]
{{- end}}
func (c *{{.Name}}Controller) Update(w http.ResponseWriter, r *http.Request) error {
	id, err := utils.ParseIDStringIsValidUUID(chi.URLParam(r, "id"))
	if err != nil {
		return apperrors.NewBadRequest("id should be a valid UUID", nil)
	}
	ifMatch, err := httputil.ParseIfMatch(r)
	if err != nil {
		return err
	}
	expectedVersion, err := strconv.Atoi(ifMatch)
	if err != nil {
		return apperrors.NewBadRequest(` + "`If-Match must be a positive integer wrapped in quotes (e.g. \"3\")`" + `, nil)
	}
	in, err := httputil.DecodeJSON[dtos.TUpdate{{.Name}}Dto](r)
	if err != nil {
		return apperrors.NewBadRequest("invalid request body", nil)
	}
	if errs := c.validator.ValidateStruct(in); len(errs) > 0 {
		return apperrors.NewValidation("invalid input", errs)
	}
	entity, err := c.svc.Update(r.Context(), id, expectedVersion, in.ToPatch())
	switch {
	case errors.Is(err, services.Err{{.Name}}VersionConflict):
		return apperrors.NewPreconditionFailed(
			"If-Match doesn't match current record version — GET to fetch the latest ETag and retry", nil)
	case errors.Is(err, services.Err{{.Name}}NotFound), errors.Is(err, gorm.ErrRecordNotFound):
		return apperrors.NewNotFound("{{.LowerName}} not found", nil)
	case err != nil:
		return apperrors.NewInternal("failed to update {{.LowerName}}", err)
	}
	w.Header().Set("ETag", {{.LowerName}}RecordVersionETag(entity.RecordVersion))
	return httputil.OK(w, dtos.T{{.Name}}ResponseDto{Data: dtos.{{.Name}}FromModel(entity)})
}

// Archive handles DELETE /{{.PluralLower}}/{id}. Idempotent semantics:
// first call returns 200 with the soft-deleted record (Stripe pattern
// — body carries the WHICH + WHEN); a second call on the same id
// returns 404 (no longer addressable via the public API — matches
// GitHub / Kubernetes); a call against a row with IsDeletable=false
// returns 409 (legitimate policy refusal).
{{- if .IncludeSwagger}}
//
//	@Summary		Archive a {{.LowerName}}
//	@Description	Soft-delete a {{.LowerName}} by ID. Idempotent: a second call returns 404.
//	@Tags			{{.PluralLower}}
//	@Produce		json
//	@Param			id	path	string	true	"{{.Name}} ID"
//	@Success		200	{object}	dtos.T{{.Name}}ResponseDto	"the soft-deleted record"
//	@Failure		400	{object}	apperrors.AppError
//	@Failure		404	{object}	apperrors.AppError	"row missing OR already deleted"
//	@Failure		409	{object}	apperrors.AppError	"{{.LowerName}} is not deletable"
//	@Failure		500	{object}	apperrors.AppError
//	@Router			/{{.PluralLower}}/{id} [delete]
{{- end}}
func (c *{{.Name}}Controller) Archive(w http.ResponseWriter, r *http.Request) error {
	id, err := utils.ParseIDStringIsValidUUID(chi.URLParam(r, "id"))
	if err != nil {
		return apperrors.NewBadRequest("id should be a valid UUID", nil)
	}
	entity, err := c.svc.Archive(r.Context(), id)
	switch {
	case errors.Is(err, services.Err{{.Name}}NotFound), errors.Is(err, gorm.ErrRecordNotFound):
		return apperrors.NewNotFound("{{.LowerName}} not found", nil)
	case errors.Is(err, services.Err{{.Name}}NotDeletable):
		return apperrors.NewConflict("{{.LowerName}} is not deletable", nil)
	case err != nil:
		return apperrors.NewInternal("failed to archive {{.LowerName}}", err)
	}
	return httputil.OK(w, dtos.T{{.Name}}ResponseDto{Data: dtos.{{.Name}}FromModel(entity)})
}
`
