package templates

// RepoInterface is the Go template for generating a repository interface.
//
// Two methods (UpdateIfVersionMatches, SoftDeleteIfDeletable) bake
// business preconditions into the SQL WHERE clause so the operations
// are atomic — there's no Find-then-Update gap for another writer to
// race through. Both return RowsAffected; service callers map 0 to a
// domain sentinel error.
var RepoInterface = `package interfaces

import (
	"context"
	"errors"

	"github.com/google/uuid"

	"{{.ModulePath}}/app/models"
)

// Err{{.Name}}NotDeletable is the typed error SoftDeleteIfDeletable
// returns when the row exists but its IsDeletable flag is false.
// Lives in the interfaces package because it's part of the contract —
// every implementation surfaces this so services can translate it
// without depending on the concrete repository type. "Not found" /
// "already deleted" flow through as gorm.ErrRecordNotFound (the
// auto-filter on gorm.DeletedAt buckets both together).
var Err{{.Name}}NotDeletable = errors.New("{{.LowerName}} is not deletable")

// {{.Name}}RepositoryInterface is the contract the {{.Name}} repository
// satisfies. Generated by ` + "`gofasta g repository`" + `.
type {{.Name}}RepositoryInterface interface {
	List(ctx context.Context, filter map[string]any, page, limit int, sort string) ([]*models.{{.Name}}, int64, error)
	FindByID(ctx context.Context, id uuid.UUID) (*models.{{.Name}}, error)
	Create(ctx context.Context, entity *models.{{.Name}}) error
	// UpdateIfVersionMatches runs an atomic UPDATE with the version check
	// folded into WHERE, then refetches in the same transaction. Returns
	// (entity, 1, nil) on success; (nil, 0, nil) when the version didn't
	// match (caller maps to Err{{.Name}}VersionConflict).
	UpdateIfVersionMatches(ctx context.Context, id uuid.UUID, expectedVersion int, fields map[string]any) (*models.{{.Name}}, int64, error)
	// SoftDeleteIfDeletable archives the row and returns the soft-
	// deleted record (Stripe-pattern 200 response). Distinguishes:
	//   (entity, nil)                       — archived, payload reflects writes
	//   (nil, gorm.ErrRecordNotFound)       — missing OR already deleted (idempotent 404)
	//   (nil, Err{{.Name}}NotDeletable)            — policy refusal (409)
	//   (nil, err)                          — infrastructure failure
	SoftDeleteIfDeletable(ctx context.Context, id uuid.UUID) (*models.{{.Name}}, error)
}
`
