package templates

// RepoInterface is the Go template for generating a repository interface.
//
// Two methods (UpdateIfVersionMatches, SoftDeleteIfDeletable) bake
// business preconditions into the SQL WHERE clause so the operations
// are atomic — there's no Find-then-Update gap for another writer to
// race through. Both return RowsAffected; service callers map 0 to a
// domain sentinel error.
var RepoInterface = `package interfaces

import (
	"context"

	"github.com/google/uuid"

	"{{.ModulePath}}/app/models"
)

// {{.Name}}RepositoryInterface is the contract the {{.Name}} repository
// satisfies. Generated by ` + "`gofasta g repository`" + `.
type {{.Name}}RepositoryInterface interface {
	List(ctx context.Context, filter map[string]any, page, limit int, sort string) ([]*models.{{.Name}}, int64, error)
	FindByID(ctx context.Context, id uuid.UUID) (*models.{{.Name}}, error)
	Create(ctx context.Context, entity *models.{{.Name}}) error
	// UpdateIfVersionMatches runs an atomic UPDATE with the version check
	// folded into WHERE, then refetches in the same transaction. Returns
	// (entity, 1, nil) on success; (nil, 0, nil) when the version didn't
	// match (caller maps to Err{{.Name}}VersionConflict).
	UpdateIfVersionMatches(ctx context.Context, id uuid.UUID, expectedVersion int, fields map[string]any) (*models.{{.Name}}, int64, error)
	// SoftDeleteIfDeletable runs an atomic UPDATE with the deletable
	// guard in WHERE. Returns RowsAffected; 0 means missing or not
	// deletable (caller maps to Err{{.Name}}NotDeletable).
	SoftDeleteIfDeletable(ctx context.Context, id uuid.UUID) (int64, error)
}
`
