package templates

// RepoInterface is the Go template for generating a repository interface.
var RepoInterface = `package interfaces

import (
	"context"

	"github.com/google/uuid"

	"{{.ModulePath}}/app/models"
)

// {{.Name}}RepositoryInterface is the contract the {{.Name}} repository
// satisfies. Generated by ` + "`gofasta g repository`" + ` — extend with
// project-specific lookups as the data-access surface grows.
type {{.Name}}RepositoryInterface interface {
	FindAll(ctx context.Context, page, limit int, sort string) ([]*models.{{.Name}}, int64, error)
	FindByID(ctx context.Context, id uuid.UUID) (*models.{{.Name}}, error)
	FindByIDAndRecordVersion(ctx context.Context, id uuid.UUID, version int) (*models.{{.Name}}, error)
	Create(ctx context.Context, entity *models.{{.Name}}) error
	Update(ctx context.Context, id uuid.UUID, fields map[string]any) error
	SoftDelete(ctx context.Context, id uuid.UUID) error
}
`
