package templates

// Repo is the Go template for generating a GORM repository.
//
// Each method opens a span so the dashboard waterfall clearly
// distinguishes repository time from service time and SQL latency
// from business-logic latency. SQL bodies themselves are surfaced by
// the devtools GORM plugin on the Recent SQL panel — the spans here
// just anchor the operation in the trace tree.
var Repo = `package repositories

import (
	"context"
	"time"

	"github.com/google/uuid"
	"go.opentelemetry.io/otel"
	"gorm.io/gorm"

	"{{.ModulePath}}/app/models"
	repoInterfaces "{{.ModulePath}}/app/repositories/interfaces"
)

// {{.LowerName}}RepositoryTracerName is the OpenTelemetry tracer scope for the
// {{.Name}} repository. Each method opens a span under this scope so SQL
// time is visible as nested bars under the service span in the dashboard.
const {{.LowerName}}RepositoryTracerName = "{{.ModulePath}}/app/repositories/{{.LowerName}}"

// Compile-time check that {{.Name}}Repository implements {{.Name}}RepositoryInterface.
var _ repoInterfaces.{{.Name}}RepositoryInterface = (*{{.Name}}Repository)(nil)

// {{.Name}}Repository is the GORM-backed data-access layer for the
// {{.Name}} resource. Generated by ` + "`gofasta g repository`" + `.
type {{.Name}}Repository struct {
	DB *gorm.DB
}

// New{{.Name}}Repository constructs a {{.Name}}Repository bound to the
// supplied GORM database handle. Wire calls this at app startup.
func New{{.Name}}Repository(db *gorm.DB) *{{.Name}}Repository {
	return &{{.Name}}Repository{DB: db}
}

// FindAll returns the paginated, sorted list of non-deleted {{.Name}}
// rows along with the total count for pagination.
func (r *{{.Name}}Repository) FindAll(ctx context.Context, page, limit int, sort string) ([]*models.{{.Name}}, int64, error) {
	ctx, span := otel.Tracer({{.LowerName}}RepositoryTracerName).Start(ctx, "{{.Name}}Repository.FindAll")
	defer span.End()

	var total int64
	query := r.DB.WithContext(ctx).Model(&models.{{.Name}}{}).Where("deleted_at IS NULL")
	if err := query.Count(&total).Error; err != nil {
		span.RecordError(err)
		return nil, 0, err
	}
	var entities []*models.{{.Name}}
	offset := (page - 1) * limit
	if err := query.Limit(limit).Offset(offset).Order(sort).Find(&entities).Error; err != nil {
		span.RecordError(err)
		return nil, 0, err
	}
	return entities, total, nil
}

// FindByID returns the row with the given ID, scoped to non-deleted
// records. Returns gorm.ErrRecordNotFound when no row matches.
func (r *{{.Name}}Repository) FindByID(ctx context.Context, id uuid.UUID) (*models.{{.Name}}, error) {
	ctx, span := otel.Tracer({{.LowerName}}RepositoryTracerName).Start(ctx, "{{.Name}}Repository.FindByID")
	defer span.End()

	var entity models.{{.Name}}
	if err := r.DB.WithContext(ctx).Where("id = ? AND deleted_at IS NULL", id).First(&entity).Error; err != nil {
		span.RecordError(err)
		return nil, err
	}
	return &entity, nil
}

// FindByIDAndRecordVersion returns the row only if its RecordVersion
// matches version and the row is not soft-deleted. Used by services
// for optimistic-locking guards before applying updates.
func (r *{{.Name}}Repository) FindByIDAndRecordVersion(ctx context.Context, id uuid.UUID, version int) (*models.{{.Name}}, error) {
	ctx, span := otel.Tracer({{.LowerName}}RepositoryTracerName).Start(ctx, "{{.Name}}Repository.FindByIDAndRecordVersion")
	defer span.End()

	var entity models.{{.Name}}
	if err := r.DB.WithContext(ctx).Where("id = ? AND deleted_at IS NULL AND record_version = ?", id, version).First(&entity).Error; err != nil {
		span.RecordError(err)
		return nil, err
	}
	return &entity, nil
}

// Create inserts a new {{.Name}} row. The framework's BeforeCreate hook
// on BaseModelImpl populates the UUID and timestamps automatically.
func (r *{{.Name}}Repository) Create(ctx context.Context, entity *models.{{.Name}}) error {
	ctx, span := otel.Tracer({{.LowerName}}RepositoryTracerName).Start(ctx, "{{.Name}}Repository.Create")
	defer span.End()

	if err := r.DB.WithContext(ctx).Create(entity).Error; err != nil {
		span.RecordError(err)
		return err
	}
	return nil
}

// Update applies a partial update to the row identified by id. Only
// keys present in the fields map are written.
func (r *{{.Name}}Repository) Update(ctx context.Context, id uuid.UUID, fields map[string]interface{}) error {
	ctx, span := otel.Tracer({{.LowerName}}RepositoryTracerName).Start(ctx, "{{.Name}}Repository.Update")
	defer span.End()

	if err := r.DB.WithContext(ctx).Model(&models.{{.Name}}{}).Where("id = ?", id).Updates(fields).Error; err != nil {
		span.RecordError(err)
		return err
	}
	return nil
}

// SoftDelete marks the row as deleted by setting deleted_at + clearing
// is_active. The is_deletable guard prevents deleting protected rows.
func (r *{{.Name}}Repository) SoftDelete(ctx context.Context, id uuid.UUID) error {
	ctx, span := otel.Tracer({{.LowerName}}RepositoryTracerName).Start(ctx, "{{.Name}}Repository.SoftDelete")
	defer span.End()

	if err := r.DB.WithContext(ctx).Model(&models.{{.Name}}{}).
		Where("id = ? AND is_deletable = ?", id, true).
		Updates(map[string]interface{}{"deleted_at": time.Now(), "is_active": false}).Error; err != nil {
		span.RecordError(err)
		return err
	}
	return nil
}
`
