package templates

// Repo is the Go template for generating a GORM repository.
//
// Atomic-write semantics: UpdateIfVersionMatches runs UPDATE +
// refetch in one transaction; SoftDeleteIfDeletable runs an UPDATE
// with the deletable guard in WHERE. Both return RowsAffected so the
// service can translate 0 to a domain sentinel.
//
// Soft-deleted rows are excluded from SELECTs automatically because
// BaseModelImpl.DeletedAt is gorm.DeletedAt — GORM adds
// `WHERE deleted_at IS NULL` to every query.
var Repo = `package repositories

import (
	"context"
	"fmt"
	"time"

	"github.com/gofastadev/gofasta/pkg/utils"
	"github.com/google/uuid"
	"go.opentelemetry.io/otel"
	"gorm.io/gorm"

	"{{.ModulePath}}/app/models"
	repoInterfaces "{{.ModulePath}}/app/repositories/interfaces"
)

// {{.LowerName}}RepositoryTracerName is the OpenTelemetry tracer scope for the
// {{.Name}} repository. Each method opens a span under this scope so SQL
// time is visible nested under its service span in the dev dashboard.
const {{.LowerName}}RepositoryTracerName = "{{.ModulePath}}/app/repositories/{{.LowerName}}"

// Compile-time check that {{.Name}}Repository implements {{.Name}}RepositoryInterface.
var _ repoInterfaces.{{.Name}}RepositoryInterface = (*{{.Name}}Repository)(nil)

// {{.Name}}Repository is the GORM-backed data-access layer for the
// {{.Name}} resource. Generated by ` + "`gofasta g repository`" + `. Fields are
// unexported — Wire injects them via the constructor.
type {{.Name}}Repository struct {
	db *gorm.DB
}

// New{{.Name}}Repository constructs a {{.Name}}Repository bound to the
// supplied GORM database handle. Wire calls this at app startup.
func New{{.Name}}Repository(db *gorm.DB) *{{.Name}}Repository {
	return &{{.Name}}Repository{db: db}
}

// List returns the paginated, sorted, filtered set of {{.PluralLower}}
// rows along with the total count for pagination.
func (r *{{.Name}}Repository) List(ctx context.Context, filter map[string]any, page, limit int, sort string) ([]*models.{{.Name}}, int64, error) {
	ctx, span := otel.Tracer({{.LowerName}}RepositoryTracerName).Start(ctx, "{{.Name}}Repository.List")
	defer span.End()

	query, err := utils.BuildQueryForAnyModel(r.db.WithContext(ctx).Model(&models.{{.Name}}{}), filter)
	if err != nil {
		span.RecordError(err)
		return nil, 0, fmt.Errorf("{{.Name}}Repository.List: build query: %w", err)
	}

	var totalCount int64
	if err := query.Count(&totalCount).Error; err != nil {
		span.RecordError(err)
		return nil, 0, fmt.Errorf("{{.Name}}Repository.List: count: %w", err)
	}
	offset := (page - 1) * limit
	var entities []*models.{{.Name}}
	if err := query.Limit(limit).Offset(offset).Order(sort).Find(&entities).Error; err != nil {
		span.RecordError(err)
		return nil, 0, fmt.Errorf("{{.Name}}Repository.List: query: %w", err)
	}
	return entities, totalCount, nil
}

// FindByID returns one row by primary key. Soft-deleted rows are
// excluded automatically by GORM's gorm.DeletedAt auto-filter.
// Returns gorm.ErrRecordNotFound when no row matches.
func (r *{{.Name}}Repository) FindByID(ctx context.Context, id uuid.UUID) (*models.{{.Name}}, error) {
	ctx, span := otel.Tracer({{.LowerName}}RepositoryTracerName).Start(ctx, "{{.Name}}Repository.FindByID")
	defer span.End()

	var entity models.{{.Name}}
	if err := r.db.WithContext(ctx).Where("id = ?", id).First(&entity).Error; err != nil {
		span.RecordError(err)
		return nil, fmt.Errorf("{{.Name}}Repository.FindByID: %w", err)
	}
	return &entity, nil
}

// Create inserts a new {{.Name}} row. The framework's BeforeCreate hook
// on BaseModelImpl populates the UUID, timestamps, and defaults.
func (r *{{.Name}}Repository) Create(ctx context.Context, entity *models.{{.Name}}) error {
	ctx, span := otel.Tracer({{.LowerName}}RepositoryTracerName).Start(ctx, "{{.Name}}Repository.Create")
	defer span.End()

	if err := r.db.WithContext(ctx).Create(entity).Error; err != nil {
		span.RecordError(err)
		return fmt.Errorf("{{.Name}}Repository.Create: %w", err)
	}
	return nil
}

// UpdateIfVersionMatches runs the optimistic-locking UPDATE with the
// version check in the WHERE clause, then refetches the row in the
// same transaction. The returned entity is exactly what THIS update
// wrote — no other writer can race in between (snapshot semantics).
//
// On version mismatch the UPDATE writes 0 rows; we return (nil, 0,
// nil) so the service can map to Err{{.Name}}VersionConflict.
//
// On success record_version is bumped in the same UPDATE so the next
// reader sees the new version.
func (r *{{.Name}}Repository) UpdateIfVersionMatches(ctx context.Context, id uuid.UUID, expectedVersion int, fields map[string]any) (*models.{{.Name}}, int64, error) {
	ctx, span := otel.Tracer({{.LowerName}}RepositoryTracerName).Start(ctx, "{{.Name}}Repository.UpdateIfVersionMatches")
	defer span.End()

	var entity models.{{.Name}}
	var affected int64
	err := r.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		fields["record_version"] = expectedVersion + 1
		res := tx.Model(&models.{{.Name}}{}).
			Where("id = ? AND record_version = ?", id, expectedVersion).
			Updates(fields)
		if res.Error != nil {
			return res.Error
		}
		affected = res.RowsAffected
		if affected == 0 {
			return nil // version mismatch — caller maps to sentinel
		}
		return tx.Where("id = ?", id).First(&entity).Error
	})
	if err != nil {
		span.RecordError(err)
		return nil, 0, fmt.Errorf("{{.Name}}Repository.UpdateIfVersionMatches: %w", err)
	}
	if affected == 0 {
		return nil, 0, nil
	}
	return &entity, affected, nil
}

// SoftDeleteIfDeletable archives the row only if its is_deletable
// flag is true. Setting deleted_at + clearing is_active happens in a
// single UPDATE; GORM's auto-filter on gorm.DeletedAt excludes the
// row from subsequent reads.
//
// Returns RowsAffected. The service maps 0 to Err{{.Name}}NotDeletable.
func (r *{{.Name}}Repository) SoftDeleteIfDeletable(ctx context.Context, id uuid.UUID) (int64, error) {
	ctx, span := otel.Tracer({{.LowerName}}RepositoryTracerName).Start(ctx, "{{.Name}}Repository.SoftDeleteIfDeletable")
	defer span.End()

	res := r.db.WithContext(ctx).Model(&models.{{.Name}}{}).
		Where("id = ? AND is_deletable = ?", id, true).
		Updates(map[string]any{"deleted_at": time.Now(), "is_active": false})
	if res.Error != nil {
		span.RecordError(res.Error)
		return 0, fmt.Errorf("{{.Name}}Repository.SoftDeleteIfDeletable: %w", res.Error)
	}
	return res.RowsAffected, nil
}
`
