package templates

// Resolvers is the Go template for generating a fully-implemented
// per-resource resolver file at app/graphql/resolvers/<snake>.resolvers.go.
//
// Written BEFORE `go tool gqlgen generate` runs: gqlgen's follow-schema
// layout maps schema/<snake>.gql 1:1 to this file and preserves method
// bodies it finds there, so pre-writing the file is what prevents the
// stock panic("not implemented") stubs from ever appearing.
//
// Constraints inherited from gqlgen (same as the skeleton's
// user.resolvers.go):
//   - ONLY resolver methods may live in this file — gqlgen relocates
//     any other declaration into a commented-out block on regeneration.
//     Shared helpers (gqlError / validationGqlError / internalGqlError)
//     live in gql_errors.go, which gqlgen does not own.
//   - Input types bind via autobind to the hand-written DTOs (the
//     schema fragment declares the DTO type names), so bodies can use
//     ToCreateInput / ToPatch / ToFilter directly.
//
// Layout awareness: the file's PATH is identical in both layouts
// (gqlgen owns the resolvers dir), but the symbols it references move
// in feature mode — per-resource symbols to `<snake>pkg`, shared dtos
// (TPaginationObjectDto) to app/shared/dtos. The template branches on
// .L.IsFeature because WriteTemplate's auto-featurize gate only fires
// for files under app/<snake>/.
var Resolvers = `package resolvers

// Per gqlgen convention, this file is regenerated by
// ` + "`go tool gqlgen generate`" + ` from the .gql schema; resolver bodies
// written here are preserved across regenerations.
//
// Only resolver METHODS belong in this file. gqlgen preserves method
// bodies but relocates anything else — plain functions, vars, types —
// into a commented-out block when it regenerates. Shared helpers live
// in gql_errors.go, which gqlgen does not own.
{{- $pkg := "dtos"}}{{- $svc := "services"}}
{{- if .L.IsFeature}}{{- $pkg = printf "%spkg" .SnakeName}}{{- $svc = $pkg}}{{- end}}

import (
	"context"
	"errors"

	"gorm.io/gorm"

{{- if .L.IsFeature}}
	"{{.ModulePath}}/app/shared/dtos"
	{{.SnakeName}}pkg "{{.ModulePath}}/app/{{.SnakeName}}"
{{- else}}
	"{{.ModulePath}}/app/dtos"
	"{{.ModulePath}}/app/services"
{{- end}}
)

// Create{{.Name}} is the resolver for the create{{.Name}} field.
func (r *mutationResolver) Create{{.Name}}(ctx context.Context, input {{$pkg}}.TCreate{{.Name}}Dto) (*{{$pkg}}.{{.Name}}, error) {
	if errs := r.Validator.ValidateStruct(input); len(errs) > 0 {
		return nil, validationGqlError(errs)
	}
	entity, err := r.{{.Name}}Service.Create(ctx, input.ToCreateInput())
	if err != nil {
		return nil, internalGqlError("failed to create {{.LowerName}}", err)
	}
	return {{$pkg}}.{{.Name}}FromModel(entity), nil
}

// Update{{.Name}} is the resolver for the update{{.Name}} field.
// GraphQL has no equivalent of HTTP's If-Match header, so id +
// recordVersion live in the input object (TUpdate{{.Name}}GraphQLInput)
// rather than as separate arguments.
func (r *mutationResolver) Update{{.Name}}(ctx context.Context, input {{$pkg}}.TUpdate{{.Name}}GraphQLInput) (*{{$pkg}}.{{.Name}}, error) {
	if errs := r.Validator.ValidateStruct(input); len(errs) > 0 {
		return nil, validationGqlError(errs)
	}
	entity, err := r.{{.Name}}Service.Update(ctx, input.ID, input.RecordVersion, input.ToPatch())
	switch {
	case errors.Is(err, {{$svc}}.Err{{.Name}}VersionConflict):
		return nil, gqlError("CONFLICT", "record version mismatch — refetch and retry")
	case errors.Is(err, {{$svc}}.Err{{.Name}}NotFound), errors.Is(err, gorm.ErrRecordNotFound):
		return nil, gqlError("NOT_FOUND", "{{.LowerName}} not found")
	case err != nil:
		return nil, internalGqlError("failed to update {{.LowerName}}", err)
	}
	return {{$pkg}}.{{.Name}}FromModel(entity), nil
}

// Archive{{.Name}} is the resolver for the archive{{.Name}} field.
// Returns the soft-deleted {{.LowerName}} payload (matching the REST
// controller's 200-with-record response). A second archive of the same
// id returns NOT_FOUND — same idempotency rule as REST's DELETE.
func (r *mutationResolver) Archive{{.Name}}(ctx context.Context, input {{$pkg}}.TArchive{{.Name}}Dto) (*{{$pkg}}.{{.Name}}, error) {
	if errs := r.Validator.ValidateStruct(input); len(errs) > 0 {
		return nil, validationGqlError(errs)
	}
	entity, err := r.{{.Name}}Service.Archive(ctx, input.ID)
	switch {
	case errors.Is(err, {{$svc}}.Err{{.Name}}NotFound), errors.Is(err, gorm.ErrRecordNotFound):
		return nil, gqlError("NOT_FOUND", "{{.LowerName}} not found")
	case errors.Is(err, {{$svc}}.Err{{.Name}}NotDeletable):
		return nil, gqlError("CONFLICT", "{{.LowerName}} is not deletable")
	case err != nil:
		return nil, internalGqlError("failed to archive {{.LowerName}}", err)
	}
	return {{$pkg}}.{{.Name}}FromModel(entity), nil
}

// FindAll{{.PluralName}} is the resolver for the findAll{{.PluralName}} field.
func (r *queryResolver) FindAll{{.PluralName}}(ctx context.Context, filters {{$pkg}}.T{{.Name}}FiltersQueryParamsDto) (*{{$pkg}}.T{{.PluralName}}ResponseDto, error) {
	if errs := r.Validator.ValidateStruct(filters); len(errs) > 0 {
		return nil, validationGqlError(errs)
	}
	f := filters.ToFilter()
	entities, total, err := r.{{.Name}}Service.List(ctx, f)
	if err != nil {
		return nil, internalGqlError("failed to list {{.PluralLower}}", err)
	}
	totalRecords := int(total)
	totalPages := 0
	if f.Limit > 0 {
		totalPages = (totalRecords + f.Limit - 1) / f.Limit
	}
	return &{{$pkg}}.T{{.PluralName}}ResponseDto{
		Data: {{$pkg}}.{{.PluralName}}FromModels(entities),
		Pagination: &dtos.TPaginationObjectDto{
			TotalRecords:   &totalRecords,
			CurrentPage:    &f.Page,
			RecordsPerPage: &f.Limit,
			TotalPages:     &totalPages,
		},
	}, nil
}

// Find{{.Name}}ByID is the resolver for the find{{.Name}}ById field.
func (r *queryResolver) Find{{.Name}}ByID(ctx context.Context, input {{$pkg}}.TFind{{.Name}}ByIDDto) (*{{$pkg}}.{{.Name}}, error) {
	if errs := r.Validator.ValidateStruct(input); len(errs) > 0 {
		return nil, validationGqlError(errs)
	}
	entity, err := r.{{.Name}}Service.Get(ctx, input.ID)
	switch {
	case errors.Is(err, {{$svc}}.Err{{.Name}}NotFound), errors.Is(err, gorm.ErrRecordNotFound):
		return nil, gqlError("NOT_FOUND", "{{.LowerName}} not found")
	case err != nil:
		return nil, internalGqlError("failed to find {{.LowerName}}", err)
	}
	return {{$pkg}}.{{.Name}}FromModel(entity), nil
}
`
