package templates

// Routes is the Go template for generating route registration for a resource.
var Routes = `package routes

import (
	"github.com/go-chi/chi/v5"
	"github.com/gofastadev/gofasta/pkg/httputil"

	"{{.ModulePath}}/app/rest/controllers"
)

// {{.Name}}Routes registers the REST surface for the {{.Name}} resource
// on the supplied chi router. Generated by ` + "`gofasta g route`" + `.
func {{.Name}}Routes(r chi.Router, c *controllers.{{.Name}}Controller) {
	r.Get("/{{.PluralSnake}}", httputil.Handle(c.List))
	r.Post("/{{.PluralSnake}}", httputil.Handle(c.Create))
	r.Get("/{{.PluralSnake}}/{id}", httputil.Handle(c.GetByID))
	r.Put("/{{.PluralSnake}}/{id}", httputil.Handle(c.Update))
	r.Delete("/{{.PluralSnake}}/{id}", httputil.Handle(c.Archive))
}
`
