package templates

// Svc is the Go template for generating a service implementation.
//
// Domain returns: methods take typed inputs (Create{{.Name}}Input,
// Update{{.Name}}Patch, List{{.PluralName}}Filter) and return *models.{{.Name}} +
// error. Sentinel errors signal known domain conditions; everything
// else is wrapped infrastructure error.
//
// No Validator dependency: the controller (or GraphQL resolver) runs
// validation before calling these methods. The service assumes valid
// input.
//
// Each method opens an OpenTelemetry span for the dev-dashboard
// trace waterfall.
var Svc = `package services

import (
	"context"
	"errors"
	"fmt"

	"github.com/gofastadev/gofasta/pkg/utils"
	"github.com/google/uuid"
	"go.opentelemetry.io/otel"
	"gorm.io/gorm"

	"{{.ModulePath}}/app/models"
	repoInterfaces "{{.ModulePath}}/app/repositories/interfaces"
)

// {{.LowerName}}ServiceTracerName is the tracer scope reported on each
// span this service opens.
const {{.LowerName}}ServiceTracerName = "{{.ModulePath}}/app/services/{{.LowerName}}"

// {{.LowerName}}SortColumns is the allowlist of database columns clients may
// sort by via the sortByField query parameter. Any other value falls back to
// created_at. This allowlist is the trust boundary between untrusted request
// input and the SQL ORDER BY clause — without it, sortByField would flow
// straight into GORM's .Order() and enable ORDER-BY SQL injection.
var {{.LowerName}}SortColumns = []string{
	"id",
	"created_at",
	"updated_at",
{{- range .Fields}}
	"{{.SnakeName}}",
{{- end}}
}

// {{.Name}}Service implements the {{.Name}}-domain business logic on top
// of the repository layer. Generated by ` + "`gofasta g service`" + `.
//
// Fields are unexported — Wire injects them via the constructor.
type {{.Name}}Service struct {
	repo repoInterfaces.{{.Name}}RepositoryInterface
}

// New{{.Name}}Service constructs a {{.Name}}Service. Wire calls this at
// app startup.
func New{{.Name}}Service(repo repoInterfaces.{{.Name}}RepositoryInterface) *{{.Name}}Service {
	return &{{.Name}}Service{repo: repo}
}

// List returns the paginated set of {{.PluralLower}} matching the filter.
func (s *{{.Name}}Service) List(ctx context.Context, filter List{{.PluralName}}Filter) ([]*models.{{.Name}}, int64, error) {
	ctx, span := otel.Tracer({{.LowerName}}ServiceTracerName).Start(ctx, "{{.Name}}Service.List")
	defer span.End()

	sort := build{{.Name}}SortClause(filter.SortField, filter.SortDesc)
	entities, total, err := s.repo.List(ctx, filter.AsRepoFilter(), filter.Page, filter.Limit, sort)
	if err != nil {
		span.RecordError(err)
		return nil, 0, fmt.Errorf("{{.Name}}Service.List: %w", err)
	}
	return entities, total, nil
}

// Get returns the {{.LowerName}} identified by id, or Err{{.Name}}NotFound
// if no row matches.
func (s *{{.Name}}Service) Get(ctx context.Context, id uuid.UUID) (*models.{{.Name}}, error) {
	ctx, span := otel.Tracer({{.LowerName}}ServiceTracerName).Start(ctx, "{{.Name}}Service.Get")
	defer span.End()

	entity, err := s.repo.FindByID(ctx, id)
	if errors.Is(err, gorm.ErrRecordNotFound) {
		return nil, Err{{.Name}}NotFound
	}
	if err != nil {
		span.RecordError(err)
		return nil, fmt.Errorf("{{.Name}}Service.Get: %w", err)
	}
	return entity, nil
}

// Create persists a new {{.LowerName}} from the supplied domain input.
func (s *{{.Name}}Service) Create(ctx context.Context, in Create{{.Name}}Input) (*models.{{.Name}}, error) {
	ctx, span := otel.Tracer({{.LowerName}}ServiceTracerName).Start(ctx, "{{.Name}}Service.Create")
	defer span.End()

	entity := &models.{{.Name}}{
{{- range .Fields}}
		{{.Name}}: in.{{.Name}},
{{- end}}
	}
	if err := s.repo.Create(ctx, entity); err != nil {
		span.RecordError(err)
		return nil, fmt.Errorf("{{.Name}}Service.Create: %w", err)
	}
	return entity, nil
}

// Update applies a partial update under optimistic locking. The
// version check + UPDATE + refetch all happen in one transaction
// inside the repo, so the returned entity is exactly what THIS update
// wrote (snapshot semantics).
//
// Returns Err{{.Name}}NotFound when no live row has that id, and
// Err{{.Name}}VersionConflict when the row exists but expectedVersion
// no longer matches the persisted value. Pass expectedVersion == -1 to
// skip the version check (the ` + "`If-Match: *`" + ` match-any precondition).
func (s *{{.Name}}Service) Update(ctx context.Context, id uuid.UUID, expectedVersion int, patch Update{{.Name}}Patch) (*models.{{.Name}}, error) {
	ctx, span := otel.Tracer({{.LowerName}}ServiceTracerName).Start(ctx, "{{.Name}}Service.Update")
	defer span.End()

	entity, affected, err := s.repo.UpdateIfVersionMatches(ctx, id, expectedVersion, patch.AsMap())
	if errors.Is(err, gorm.ErrRecordNotFound) {
		return nil, Err{{.Name}}NotFound
	}
	if err != nil {
		span.RecordError(err)
		return nil, fmt.Errorf("{{.Name}}Service.Update: %w", err)
	}
	if affected == 0 {
		return nil, Err{{.Name}}VersionConflict
	}
	return entity, nil
}

// Archive soft-deletes the {{.LowerName}} and returns the deleted
// record so the caller can respond 200-with-payload (Stripe pattern).
// Three outcomes the REST controller maps to distinct HTTP statuses:
//
//   - Err{{.Name}}NotFound — row missing OR already soft-deleted (404).
//   - Err{{.Name}}NotDeletable — row exists but IsDeletable=false (409).
//   - (*models.{{.Name}}, nil) — soft-deleted; payload carries the
//     freshly-stamped DeletedAt + IsActive=false.
func (s *{{.Name}}Service) Archive(ctx context.Context, id uuid.UUID) (*models.{{.Name}}, error) {
	ctx, span := otel.Tracer({{.LowerName}}ServiceTracerName).Start(ctx, "{{.Name}}Service.Archive")
	defer span.End()

	entity, err := s.repo.SoftDeleteIfDeletable(ctx, id)
	switch {
	case errors.Is(err, gorm.ErrRecordNotFound):
		return nil, Err{{.Name}}NotFound
	case errors.Is(err, repoInterfaces.Err{{.Name}}NotDeletable):
		return nil, Err{{.Name}}NotDeletable
	case err != nil:
		span.RecordError(err)
		return nil, fmt.Errorf("{{.Name}}Service.Archive: %w", err)
	}
	return entity, nil
}

// build{{.Name}}SortClause turns the typed sort intent into the ORDER BY
// string GORM expects, validating the requested field against
// {{.LowerName}}SortColumns first. utils.SafeOrderBy guarantees the returned
// column is one of the allowlisted names (or the created_at fallback), so the
// value composed here can never carry a SQL-injection payload from the
// sortByField query parameter.
func build{{.Name}}SortClause(field string, desc bool) string {
	col := utils.SafeOrderBy(field, desc, {{.LowerName}}SortColumns, "created_at")
	direction := "ASC"
	if col.Desc {
		direction = "DESC"
	}
	return col.Column.Name + " " + direction
}
`
