package templates

// Svc is the Go template for generating a service implementation.
//
// Each method opens an OpenTelemetry span covering its body. This
// feeds the dev-dashboard trace waterfall: when a developer watches a
// request roll in, the controller → service → repository spans nest
// correctly and every span carries its entry stack (captured by the
// devtools span processor at OnStart). In production the spans go to
// whichever exporter pkg/observability is configured with; if tracing
// is disabled the tracer is a no-op and the cost is a single function
// call per boundary.
var Svc = `package services

import (
	"context"
	"errors"
	"fmt"
	"math"
	"net/http"

	"github.com/gofastadev/gofasta/pkg/utils"
	"go.opentelemetry.io/otel"
	"gorm.io/gorm"

	"{{.ModulePath}}/app/dtos"
	"{{.ModulePath}}/app/models"
	repoInterfaces "{{.ModulePath}}/app/repositories/interfaces"
	svcInterfaces "{{.ModulePath}}/app/services/interfaces"
	"{{.ModulePath}}/app/validators"
)

// {{.LowerName}}ServiceTracerName is the tracer scope reported on each
// span this service opens. Matches the instrumentation library pattern
// used elsewhere in the scaffold so traces group cleanly in the
// dashboard.
const {{.LowerName}}ServiceTracerName = "{{.ModulePath}}/app/services/{{.LowerName}}"

// Compile-time check that {{.Name}}Service implements {{.Name}}ServiceInterface.
var _ svcInterfaces.{{.Name}}ServiceInterface = (*{{.Name}}Service)(nil)

// {{.Name}}Service implements the {{.Name}}-domain business logic on top
// of the repository layer. Generated by ` + "`gofasta g service`" + ` —
// fill in the model↔DTO mapping in cast{{.Name}}ToDto and add
// project-specific behavior in the methods below.
type {{.Name}}Service struct {
	{{.Name}}Repo repoInterfaces.{{.Name}}RepositoryInterface
	Validator     *validators.AppValidator
}

// New{{.Name}}Service constructs a {{.Name}}Service bound to the
// supplied repository + validator. Wire calls this at app startup.
func New{{.Name}}Service(repo repoInterfaces.{{.Name}}RepositoryInterface, validator *validators.AppValidator) *{{.Name}}Service {
	return &{{.Name}}Service{
		{{.Name}}Repo: repo,
		Validator:     validator,
	}
}

// FindAll returns the paginated set of {{.Name}} records matching the
// filters, alongside the pagination metadata for client-side rendering.
func (s *{{.Name}}Service) FindAll(ctx context.Context, filters dtos.{{.Name}}FiltersDto) (*dtos.T{{.PluralName}}ResponseDto, error) {
	ctx, span := otel.Tracer({{.LowerName}}ServiceTracerName).Start(ctx, "{{.Name}}Service.FindAll")
	defer span.End()

	paginator := utils.PreparePaginating{PageFilters: filters.Pagination, Sorting: filters.Sorting}
	page := paginator.GetPage()
	limit := paginator.GetLimit()

	entities, totalCount, err := s.{{.Name}}Repo.FindAll(ctx, page, limit, paginator.GetSort())
	if err != nil {
		span.RecordError(err)
		return nil, fmt.Errorf("{{.Name}}Service.FindAll: %w", err)
	}

	items := make([]*dtos.{{.Name}}, 0, len(entities))
	for _, e := range entities {
		items = append(items, cast{{.Name}}ToDto(e))
	}

	totalRecords := int(totalCount)
	totalPages := int(math.Ceil(float64(totalCount) / float64(limit)))
	return &dtos.T{{.PluralName}}ResponseDto{
		Data: items,
		Pagination: &dtos.TPaginationObjectDto{
			TotalRecords: &totalRecords, CurrentPage: &page,
			RecordsPerPage: &limit, TotalPages: &totalPages,
		},
	}, nil
}

// FindByID returns the {{.Name}} identified by input.ID. Returns
// validation errors in-band; surfaces repository errors as Go errors.
func (s *{{.Name}}Service) FindByID(ctx context.Context, input dtos.TFind{{.Name}}ByIDDto) (*dtos.T{{.Name}}ResponseDto, error) {
	ctx, span := otel.Tracer({{.LowerName}}ServiceTracerName).Start(ctx, "{{.Name}}Service.FindByID")
	defer span.End()

	if errs := s.Validator.ValidateStruct(input); len(errs) > 0 {
		return &dtos.T{{.Name}}ResponseDto{Errors: errs}, nil
	}
	entity, err := s.{{.Name}}Repo.FindByID(ctx, input.ID)
	if err != nil {
		span.RecordError(err)
		return nil, fmt.Errorf("{{.Name}}Service.FindByID: %w", err)
	}
	return &dtos.T{{.Name}}ResponseDto{Data: cast{{.Name}}ToDto(entity)}, nil
}

// Create validates the input, persists a new {{.Name}}, and returns the
// freshly-persisted record. Validation failures return as Errors in the
// response (HTTP 200 with body); only infrastructure errors bubble up.
func (s *{{.Name}}Service) Create(ctx context.Context, input dtos.TCreate{{.Name}}Dto) (*dtos.T{{.Name}}ResponseDto, error) {
	ctx, span := otel.Tracer({{.LowerName}}ServiceTracerName).Start(ctx, "{{.Name}}Service.Create")
	defer span.End()

	if errs := s.Validator.ValidateStruct(input); len(errs) > 0 {
		return &dtos.T{{.Name}}ResponseDto{Errors: errs}, nil
	}
	entity := &models.{{.Name}}{
		// TODO: Map input fields to model fields
	}
	if err := s.{{.Name}}Repo.Create(ctx, entity); err != nil {
		span.RecordError(err)
		return nil, fmt.Errorf("{{.Name}}Service.Create: %w", err)
	}
	return &dtos.T{{.Name}}ResponseDto{Data: cast{{.Name}}ToDto(entity)}, nil
}

// Update applies a partial update under optimistic locking. The
// caller's RecordVersion must match the persisted version or the update
// is rejected with a structured error.
func (s *{{.Name}}Service) Update(ctx context.Context, input dtos.TUpdate{{.Name}}Dto) (*dtos.T{{.Name}}ResponseDto, error) {
	ctx, span := otel.Tracer({{.LowerName}}ServiceTracerName).Start(ctx, "{{.Name}}Service.Update")
	defer span.End()

	if errs := s.Validator.ValidateStruct(input); len(errs) > 0 {
		return &dtos.T{{.Name}}ResponseDto{Errors: errs}, nil
	}
	// Optimistic-locking guard: distinguish "version mismatch" (which
	// is a user-recoverable validation error) from "DB outage" (which
	// must propagate). The original ` + "`if found, _ := ...`" + ` pattern
	// dropped infrastructure errors and showed them as wrong-version,
	// hiding real failures.
	found, err := s.{{.Name}}Repo.FindByIDAndRecordVersion(ctx, input.ID, input.RecordVersion)
	if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
		span.RecordError(err)
		return nil, fmt.Errorf("{{.Name}}Service.Update: lock check: %w", err)
	}
	if found == nil || errors.Is(err, gorm.ErrRecordNotFound) {
		fieldName := "recordVersion"
		return &dtos.T{{.Name}}ResponseDto{Errors: []*dtos.TCommonAPIErrorDto{{lbrace}}{{lbrace}}FieldName: &fieldName, Message: "The record version you passed is not matching"{{rbrace}}{{rbrace}}}, nil
	}
	fields := utils.ConvertStructToMap(input)
	if err := s.{{.Name}}Repo.Update(ctx, input.ID, fields); err != nil {
		span.RecordError(err)
		return nil, fmt.Errorf("{{.Name}}Service.Update: persist: %w", err)
	}
	updated, err := s.{{.Name}}Repo.FindByID(ctx, input.ID)
	if err != nil {
		span.RecordError(err)
		return nil, fmt.Errorf("{{.Name}}Service.Update: refetch: %w", err)
	}
	return &dtos.T{{.Name}}ResponseDto{Data: cast{{.Name}}ToDto(updated)}, nil
}

// Archive soft-deletes the {{.Name}} identified by input.ID, after the
// is_record_deletable validator confirms the row may be archived.
func (s *{{.Name}}Service) Archive(ctx context.Context, input dtos.TArchive{{.Name}}Dto) (*dtos.TCommonResponseDto, error) {
	ctx, span := otel.Tracer({{.LowerName}}ServiceTracerName).Start(ctx, "{{.Name}}Service.Archive")
	defer span.End()

	if errs := s.Validator.ValidateStruct(input); len(errs) > 0 {
		return &dtos.TCommonResponseDto{Errors: errs}, nil
	}
	if err := s.{{.Name}}Repo.SoftDelete(ctx, input.ID); err != nil {
		span.RecordError(err)
		return nil, fmt.Errorf("{{.Name}}Service.Archive: %w", err)
	}
	status := http.StatusOK
	message := "Success"
	return &dtos.TCommonResponseDto{Status: status, Message: &message}, nil
}

func cast{{.Name}}ToDto(e *models.{{.Name}}) *dtos.{{.Name}} {
	dto := &dtos.{{.Name}}{
		ID: e.ID, RecordVersion: e.RecordVersion,
		CreatedAt: e.CreatedAt, UpdatedAt: e.UpdatedAt,
		IsActive: e.IsActive, IsDeletable: e.IsDeletable,
		// TODO: Map remaining model fields to DTO fields
	}
	// Only surface DeletedAt when the row has actually been soft-deleted
	// (gorm.DeletedAt.Valid == true). A non-nil pointer to a zero time
	// would render as "0001-01-01T00:00:00Z" in JSON instead of being
	// omitted via the omitempty tag.
	if e.DeletedAt.Valid {
		t := e.DeletedAt.Time
		dto.DeletedAt = &t
	}
	return dto
}
`
