package templates

// Svc is the Go template for generating a service implementation.
//
// Domain returns: methods take typed inputs (Create{{.Name}}Input,
// Update{{.Name}}Patch, List{{.PluralName}}Filter) and return *models.{{.Name}} +
// error. Sentinel errors signal known domain conditions; everything
// else is wrapped infrastructure error.
//
// No Validator dependency: the controller (or GraphQL resolver) runs
// validation before calling these methods. The service assumes valid
// input.
//
// Each method opens an OpenTelemetry span for the dev-dashboard
// trace waterfall.
var Svc = `package services

import (
	"context"
	"errors"
	"fmt"

	"github.com/google/uuid"
	"go.opentelemetry.io/otel"
	"gorm.io/gorm"

	"{{.ModulePath}}/app/models"
	repoInterfaces "{{.ModulePath}}/app/repositories/interfaces"
)

// {{.LowerName}}ServiceTracerName is the tracer scope reported on each
// span this service opens.
const {{.LowerName}}ServiceTracerName = "{{.ModulePath}}/app/services/{{.LowerName}}"

// {{.Name}}Service implements the {{.Name}}-domain business logic on top
// of the repository layer. Generated by ` + "`gofasta g service`" + `.
//
// Fields are unexported — Wire injects them via the constructor.
type {{.Name}}Service struct {
	repo repoInterfaces.{{.Name}}RepositoryInterface
}

// New{{.Name}}Service constructs a {{.Name}}Service. Wire calls this at
// app startup.
func New{{.Name}}Service(repo repoInterfaces.{{.Name}}RepositoryInterface) *{{.Name}}Service {
	return &{{.Name}}Service{repo: repo}
}

// List returns the paginated set of {{.PluralLower}} matching the filter.
func (s *{{.Name}}Service) List(ctx context.Context, filter List{{.PluralName}}Filter) ([]*models.{{.Name}}, int64, error) {
	ctx, span := otel.Tracer({{.LowerName}}ServiceTracerName).Start(ctx, "{{.Name}}Service.List")
	defer span.End()

	sort := build{{.Name}}SortClause(filter.SortField, filter.SortDesc)
	entities, total, err := s.repo.List(ctx, filter.AsRepoFilter(), filter.Page, filter.Limit, sort)
	if err != nil {
		span.RecordError(err)
		return nil, 0, fmt.Errorf("{{.Name}}Service.List: %w", err)
	}
	return entities, total, nil
}

// Get returns the {{.LowerName}} identified by id, or Err{{.Name}}NotFound
// if no row matches.
func (s *{{.Name}}Service) Get(ctx context.Context, id uuid.UUID) (*models.{{.Name}}, error) {
	ctx, span := otel.Tracer({{.LowerName}}ServiceTracerName).Start(ctx, "{{.Name}}Service.Get")
	defer span.End()

	entity, err := s.repo.FindByID(ctx, id)
	if errors.Is(err, gorm.ErrRecordNotFound) {
		return nil, Err{{.Name}}NotFound
	}
	if err != nil {
		span.RecordError(err)
		return nil, fmt.Errorf("{{.Name}}Service.Get: %w", err)
	}
	return entity, nil
}

// Create persists a new {{.LowerName}} from the supplied domain input.
func (s *{{.Name}}Service) Create(ctx context.Context, in Create{{.Name}}Input) (*models.{{.Name}}, error) {
	ctx, span := otel.Tracer({{.LowerName}}ServiceTracerName).Start(ctx, "{{.Name}}Service.Create")
	defer span.End()

	entity := &models.{{.Name}}{
		// TODO: Map input fields to model fields
		// e.g. FieldName: in.FieldName,
	}
	if err := s.repo.Create(ctx, entity); err != nil {
		span.RecordError(err)
		return nil, fmt.Errorf("{{.Name}}Service.Create: %w", err)
	}
	return entity, nil
}

// Update applies a partial update under optimistic locking. The
// version check + UPDATE + refetch all happen in one transaction
// inside the repo, so the returned entity is exactly what THIS update
// wrote (snapshot semantics).
//
// Returns Err{{.Name}}VersionConflict when expectedVersion no longer
// matches the persisted value.
func (s *{{.Name}}Service) Update(ctx context.Context, id uuid.UUID, expectedVersion int, patch Update{{.Name}}Patch) (*models.{{.Name}}, error) {
	ctx, span := otel.Tracer({{.LowerName}}ServiceTracerName).Start(ctx, "{{.Name}}Service.Update")
	defer span.End()

	entity, affected, err := s.repo.UpdateIfVersionMatches(ctx, id, expectedVersion, patch.AsMap())
	if err != nil {
		span.RecordError(err)
		return nil, fmt.Errorf("{{.Name}}Service.Update: %w", err)
	}
	if affected == 0 {
		return nil, Err{{.Name}}VersionConflict
	}
	return entity, nil
}

// Archive soft-deletes the {{.LowerName}}. The is_deletable flag is
// checked inside the SQL WHERE clause so the operation is atomic.
// Returns Err{{.Name}}NotDeletable when the row is missing OR is
// flagged as not deletable.
func (s *{{.Name}}Service) Archive(ctx context.Context, id uuid.UUID) error {
	ctx, span := otel.Tracer({{.LowerName}}ServiceTracerName).Start(ctx, "{{.Name}}Service.Archive")
	defer span.End()

	affected, err := s.repo.SoftDeleteIfDeletable(ctx, id)
	if err != nil {
		span.RecordError(err)
		return fmt.Errorf("{{.Name}}Service.Archive: %w", err)
	}
	if affected == 0 {
		return Err{{.Name}}NotDeletable
	}
	return nil
}

// build{{.Name}}SortClause turns the typed sort intent into the string
// GORM expects. The caller has already sanitized SortField (whitelist
// or regex) — this just composes the clause.
func build{{.Name}}SortClause(field string, desc bool) string {
	if field == "" {
		field = "created_at"
	}
	if desc {
		return field + " DESC"
	}
	return field + " ASC"
}
`
