package templates

// SvcInterface is the Go template for generating a service interface.
//
// The contract uses domain inputs (CreateXInput, UpdateXPatch,
// ListXFilter — defined in app/services/<lower>_inputs.go) and
// returns *models.X + error. Sentinel errors (defined in
// app/services/<lower>_errors.go) signal known domain conditions.
// Validation is the controller's responsibility — by the time a
// method here is called, the input is already valid.
var SvcInterface = `package interfaces

import (
	"context"

	"github.com/google/uuid"

	"{{.ModulePath}}/app/models"
	"{{.ModulePath}}/app/services"
)

// {{.Name}}ServiceInterface is the contract the {{.Name}} service
// satisfies. Generated by ` + "`gofasta g service`" + ` — extend with
// project-specific operations as the business logic grows.
type {{.Name}}ServiceInterface interface {
	List(ctx context.Context, filter services.List{{.PluralName}}Filter) ([]*models.{{.Name}}, int64, error)
	Get(ctx context.Context, id uuid.UUID) (*models.{{.Name}}, error)
	Create(ctx context.Context, in services.Create{{.Name}}Input) (*models.{{.Name}}, error)
	Update(ctx context.Context, id uuid.UUID, expectedVersion int, patch services.Update{{.Name}}Patch) (*models.{{.Name}}, error)
	Archive(ctx context.Context, id uuid.UUID) error
}
`
